services:
  _defaults:
    autowire: true
    autoconfigure: true
  Pixel\GalleryBundle\Controller\Website\:
    resource: '../../Controller/Website'

  Pixel\GalleryBundle\Twig\SettingsExtension:
    public: false
    autowire: true
    tags:
      - {name: twig.extension}